### ISSUE TITLE
Package can't be downloaded due to proxy settings

### ISSUE THREAD

**Issue by ghost** [atom/atom-package-downloader#1] opened 2015-04-30 11:12 UTC
First of all, I don't know where this belongs as there is no "network"-section, so I'm posting where this issue happened to me.

When trying to install packages it fails on downloading them due to our companys proxy server.
For which the app uses http (or https or ftp) for downlading so it has to ask the user for the credentials to pass through it.
Or just put a box for entering proxy settings into the settings-tab.

Turning off any companys proxy or adding exception isn't any solution.

**Comment by sanicki** [comment] 2015-05-02 17:29
Duplicate of https://github.com/atom/atom/issues/5913, please subscribe there for updates.

**Comment by izuzak** [comment] 2015-05-04 17:04
@alsternerd You can find instructions on configuring apm to work with a proxy [here](https://github.com/atom/apm#behind-a-firewall). If you've already done that, check out atom/atom#5913 which @sanicki linked to. If that's not the problem you're seeing -- please provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues). Thanks!

**Closed as completed by izuzak** 2015-05-04 17:04 UTC
Labels: duplicate
